- name: Install packages and harden Container
  hosts: all
  become: true
  tasks:
    - name: Update and upgrade packages
      ansible.builtin.apt:
        update_cache: true
        upgrade: dist

    - name: Install packages
      ansible.builtin.apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
          - chkrootkit
          - fail2ban
          - sudo
          - apt-listbugs
          - apt-show-versions
          - needrestart
          - libpam-tmpdir
          - libpam-passwdqc
        state: present

    - name: Enable and start fail2ban service
      ansible.builtin.service:
        name: fail2ban
        state: started
        enabled: true

    - name: Run chkrootkit scan
      ansible.builtin.command: chkrootkit
      register: chkrootkit_scan
      changed_when: false

    - name: Display chkrootkit scan results
      ansible.builtin.debug:
        msg: "chkrootkit scan results: {{ chkrootkit_scan.stdout }}"

    - name: Update crontab to run chkrootkit daily
      ansible.builtin.cron:
        name: "Run chkrootkit daily"
        minute: "0"
        hour: "2"
        job: "/usr/sbin/chkrootkit > /var/log/chkrootkit.log 2>&1"

    - name: Update crontab to run Lynis scan weekly
      ansible.builtin.cron:
        name: "Run Lynis scan weekly"
        minute: "0"
        hour: "3"
        weekday: "0"
        job: "/usr/bin/lynis audit system > /var/log/lynis.log 2>&1"

    - name: Update crontab to run updates weekly
      ansible.builtin.cron:
        name: "Run system updates weekly"
        minute: "0"
        hour: "4"
        weekday: "0"
        job: "/usr/bin/apt update && /usr/bin/apt upgrade -y > /var/log/apt-updates.log 2>&1"

    - name: Add Wazuh user
      ansible.builtin.user:
        name: wazuh
        comment: "Wazuh user"
        shell: /bin/bash
        password: "{{ lookup('env', 'wazuh_build_pass') | password_hash('sha512') }}"

    - name: Add Wazuh public Key to authorized_keys
      ansible.posix.authorized_key:
        user: wazuh
        key: "{{ lookup('env', 'wazuh_public_key') }}"
        state: present

    - name: Create a sudoers drop-in file for wazuh
      ansible.builtin.copy:
        dest: /etc/sudoers.d/wazuh
        content: |
          wazuh ALL=(ALL) NOPASSWD: ALL
        owner: root
        group: root
        mode: '0440'
        validate: 'visudo -cf %s'

    - name: Create backup of jail.conf
      ansible.builtin.copy:
        src: /etc/fail2ban/jail.conf
        dest: /etc/fail2ban/jail.local
        remote_src: true
        owner: root
        group: root
        mode: '0644'
        backup: true

    - name: Configure etc/issue to display a custom message
      ansible.builtin.lineinfile:
        path: /etc/issue
        line: "WARNING: Only authorized users are allowed to access this system. Unauthorized access is strictly prohibited."

    - name: Configure etc/issue.net to display a custom message
      ansible.builtin.lineinfile:
        path: /etc/issue.net
        line: "WARNING: Only authorized users are allowed to access this system. Unauthorized access is strictly prohibited."

    - name: Configure Postfix
      ansible.builtin.lineinfile:
        path: /etc/postfix/main.cf
        line: "{{ item.line }}"
        regexp: "{{ item.regexp }}"
        state: present
      loop:
        - { regexp: '^#?smtpd_banner\s', line: 'smtpd_banner = $myhostname ESMTP\' }
      notify: Restart Postfix

    - name: Configure Backup Name server
      ansible.builtin.lineinfile:
        path: /etc/resolv.conf
        line: "nameserver 9.9.9.9"

    - name: Configure etc/login.defs
      ansible.builtin.lineinfile:
        path: /etc/login.defs
        line: "{{ item.line }}"
        regexp: "{{ item.regexp }}"
        state: present
      loop:
        - { regexp: '^#?UMASK\s', line: 'UMASK 027' }
        - { regexp: '^#?ENCRYPT_METHOD\s', line: 'ENCRYPT_METHOD SHA512' }
        - { regexp: '^#?SHA_CRYPT_MIN_ROUNDS\s', line: 'SHA_CRYPT_MIN_ROUNDS 600000' }
        - { regexp: '^#?SHA_CRYPT_MAX_ROUNDS\s', line: 'SHA_CRYPT_MAX_ROUNDS 656000' }
        - { regexp: '^#?PASS_MAX_DAYS\s', line: 'PASS_MAX_DAYS 100' }
        - { regexp: '^#?PASS_WARN_AGE\s', line: 'PASS_WARN_AGE 7' }
        - { regexp: '^#?PASS_MIN_DAYS\s', line: 'PASS_MIN_DAYS 1' }

    - name: Autoremove old packages and clean up
      ansible.builtin.apt:
        autoremove: true
        autoclean: true

    - name: Configure secure SSH protocol settings
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
        state: present
        validate: /usr/sbin/sshd -t -f %s
      loop:
        - { regexp: '^#?Port\s', line: "Port 2222" }
        - { regexp: '^#?PermitRootLogin\s', line: 'PermitRootLogin no' }
        - { regexp: '^#?PasswordAuthentication\s', line: 'PasswordAuthentication no' }
        - { regexp: '^#?PermitEmptyPasswords\s', line: 'PermitEmptyPasswords no' }
        - { regexp: '^#?MaxAuthTries\s', line: 'MaxAuthTries 3' }
        - { regexp: '^#?PubkeyAuthentication\s', line: 'PubkeyAuthentication yes' }
        - { regexp: '^#?ClientAliveInterval\s', line: 'ClientAliveInterval 300' }
        - { regexp: '^#?ClientAliveCountMax\s', line: 'ClientAliveCountMax 2' }
        - { regexp: '^#?X11Forwarding\s', line: 'X11Forwarding no' }
        - { regexp: '^#?AllowTcpForwarding\s', line: 'AllowTcpForwarding no' }
        - { regexp: '^#?AllowAgentForwarding\s', line: 'AllowAgentForwarding no' }
        - { regexp: '^#?IgnoreRhosts\s', line: 'IgnoreRhosts yes' }
        - { regexp: '^#?TCPKeepAlive\s', line: 'TCPKeepAlive no' }
        - { regexp: '^#?MaxSessions\s', line: 'MaxSessions 2' }
        - { regexp: '^#?LogLevel\s', line: 'LogLevel VERBOSE' }
      notify: Restart sshd

  handlers:
    - name: Restart Postfix
      ansible.builtin.service:
        name: postfix
        state: restarted
  
    - name: Restart sshd
      ansible.builtin.service:
        name: ssh
        state: restarted
