- name: Lynus installation and scan
  hosts: all
  become: true
  tasks:
    - name: Install Lynis
      ansible.builtin.apt:
        name: lynis
        state: present

    - name: Start Lynis service
      ansible.builtin.service:
        name: lynis
        state: started
        enabled: true

    - name: Verify Lynis installation
      ansible.builtin.command: lynis --version
      register: lynis_version
      changed_when: false

    - name: Display Lynis version
      ansible.builtin.debug:
        msg: "Lynis version installed: {{ lynis_version.stdout }}"

    - name: Run Lynis Scan
      ansible.builtin.command: lynis audit system
      changed_when: false

    - name: Capture Lynis Scan results
      ansible.builtin.command: grep -E 'hardening_index|suggestion' /var/log/lynis-report.dat
      register: lynis_audit
      changed_when: false
      failed_when: lynis_audit.rc != 0 and lynis_audit.rc != 1

    - name: Display Lynis scan results
      ansible.builtin.debug:
        msg: "Lynis scan results: {{ lynis_audit.stdout }}"
