name: Terraform Deploy

on: workflow_dispatch

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: 'true'

jobs:

  test:
    runs-on: [self-hosted, linux, x64, wazuh, terraform, ansible]
    defaults:
      run:
        working-directory: ./terraform
    steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Set up Terraform
          uses: hashicorp/setup-terraform@v4
          with:
            terraform_version: 1.14.6
            terraform_wrapper: false
        
        - name: Terraform Init
          run: terraform init

        - name: Terraform Format check
          run: terraform fmt -check -recursive
        
        - name: Terraform Validate
          run: terraform validate

  terraform:
    runs-on: [self-hosted, linux, x64, wazuh, terraform, ansible]
    needs: test
    env:
      TF_VAR_pve_host: ${{ secrets.PM_API_URL }}
      TF_VAR_terraform_token: ${{ secrets.TERRAFORM_API_TOKEN }}
      TF_VAR_terraform_user: ${{ secrets.PM_API_TOKEN_ID }}
      TF_VAR_terraform_api_key: ${{ secrets.TERRAFORM_API_TOK }}
      TF_VAR_terraform_build_pass: ${{ secrets.WAZUH_BUILD_PASSWORD }}
      TF_VAR_terraform_build_ssh_key: ${{ secrets.WAZUH_BUILD_PUBKEY }}
    defaults:
      run:
        working-directory: ./terraform
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v4
        with:
          terraform_version: 1.14.6
          terraform_wrapper: false

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        run: terraform apply -auto-approve

      - name: Terraform Output
        id: terraform_output
        run: terraform output -json > terraform_output.json

      - name: Export Container IP
        id: export_ip
        run: echo "container_ip=$(terraform output -raw container_ip)" >> "$GITHUB_OUTPUT"

    outputs:
      container_ip: ${{ steps.export_ip.outputs.container_ip }}
    
  Post:
    runs-on: [self-hosted, linux, x64, wazuh, terraform, ansible]
    needs: terraform
    env:
      CONTAINER_IP: ${{ needs.terraform.outputs.container_ip }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Connection Test
        run: |
          echo "Testing connection to the deployed container..."
          ping -c 4 $CONTAINER_IP